---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emp-seller-service
  namespace: backend
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emp-seller-service
