---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: emp-catalogue-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: emp-catalogue-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emp-catalogue-service
    spec:
      containers:
      - image: 656600766668.dkr.ecr.ap-south-1.amazonaws.com/emp-catalogue-service:d8b02c120230417065625
        imagePullPolicy: Always
        name: emp-catalogue-service
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 750m
            memory: 750Mi
          requests:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - configMapRef:
            name: emp-catalogue-service-cm
        - secretRef:
            name: emp-catalogue-service-secret
        livenessProbe:
          httpGet:
            path: /emp-catalogue-service/actuator
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - name: emp-catalogue-ca-pem
          mountPath: /etc/ssl/certs/rds-combined-ca-bundle.pem
          subPath: rds-combined-ca-bundle.pem
          readOnly: false
      volumes:
      - name: emp-catalogue-ca-pem
        configMap:
          name: emp-catalogue-ca-pem



