variable project {}
variable env {}
variable region {}
variable vpc_id {}
variable subnet1_id {}
variable subnet2_id {}
variable tnaCodebuildName {}
variable security_group_id {}
variable AWS_ACCESS_KEY_ID {}
variable AWS_SECRET_ACCESS_KEY {}
variable sourceCodeUrl {}
variable tna_repo_name {}
variable source_repo_branch {}
variable repo_branch {}
variable s3_bucket {}
variable pipeline_role {}
variable build_role {}
variable cpoCodebuildName {}
variable cpo_repo_name {}
