---
apiVersion: v1
kind: Service
metadata:
  name: emp-configuration-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: '8086'
    alb.ingress.kubernetes.io/healthcheck-path: /emp-configuration-service/actuator
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emp-configuration-service
