---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emp-notification-service
  namespace: backend
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      run: emp-notification-service
