---
apiVersion: v1
kind: Service
metadata:
  name: emp-notification-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: '8085'
    alb.ingress.kubernetes.io/healthcheck-path: /emp-notification-service/actuator/health
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8085
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emp-notification-service

