variable project {}
variable env {}
variable region {}
variable vpc_id {}
variable subnet1_id {}
variable subnet2_id {}
variable sellerCodebuildName {}
variable security_group_id {}
variable AWS_ACCESS_KEY_ID {}
variable AWS_SECRET_ACCESS_KEY {}
variable sourceCodeUrl {}
variable seller_repo_name {}
variable source_repo_branch {}
variable repo_branch {}
variable buyer_repo_name {}
variable user_repo_name {}
variable rfq_repo_name {}
variable react_repo_name {}
variable catalogue_repo_name {}
variable configuration_repo_name {}
variable notification_repo_name {}
variable buyerCodebuildName {}
variable userCodebuildName {}
variable rfqCodebuildName {}
variable reactCodebuildName {}
variable catalogueCodebuildName {}
variable configurationCodebuildName {}
variable notificationCodebuildName {}
variable s3_bucket {}
variable pipeline_role {}
variable build_role {}