---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::656600766668:role/EKS-AMP-ServiceAccount-Role"
