apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-catalogue-service-cm
data:
  server.port: "8082"

  spring.application.name: emp-catalogue-service
  spring.jpa.generate-ddl: "false"

  spring.datasource.url: jdbc:mysql://emp-qa-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/catalogue?createDatabaseIfNotExist=true
  spring.datasource.username: root

  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  #spring.jpa.hibernate.ddl-auto=validate

  opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
  spring.data.mongodb.uri: mongodb://empdoc:Indianteam1983@docdb-2023-04-18-05-48-15.chaqp2ysfjmh.ap-south-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&retryWrites=false
  spring.data.mongodb.database: catalogue_qa
  spring.data.mongodb.username: empdoc

  spring.data.mongodb.authentication-database: admin
  logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG