apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-buyer-service-cm
data:
  server.port: "8087"

  spring.application.name: emp-buyer-service
  server.servlet.context-path: /buyer
  spring.jpa.generate-ddl: "false"

  spring.datasource.url: jdbc:mysql://emp-dev-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/buyer?createDatabaseIfNotExist=true
  spring.datasource.username: root
 
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  #spring.jpa.hibernate.ddl-auto: validate

  #opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  spring.kafka.consumer.bootstrap-servers: boot-lune7eun.c2.kafka-serverless.ap-south-1.amazonaws.com:9098
  #spring.kafka.consumer.group-id= test-consumer-group
  #spring.kafka.consumer.auto-offset-reset= earliest
  #spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
  #spring.kafka.consumer.value-deserializer= org.apache.kafka.common.serialization.StringDeserializer

  catalogue-service.url: http://emp-catalogue-service/emp-catalogue-service
  catalogue-service.name: emp-catalogue-service

  user-service.name: emp-user-service
  user-service.url: http://emp-user-service/emp-user-service

  configuration-service.name: emp-configuration-service
  configuration-service.url: http://emp-configuration-service/emp-configuration-service
  configuration-service.save-metadata-url: /document/saveDocumentMetadata

  buyer.create.notification.topic: test1