apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-catalogue-service-cm
data:
  server.port: "8082"

  spring.application.name: emp-catalogue-service
  spring.jpa.generate-ddl: "false"

  spring.datasource.url: jdbc:mysql://emp-dev-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/catalogue?createDatabaseIfNotExist=true
  spring.datasource.username: root

  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  #spring.jpa.hibernate.ddl-auto=validate

  opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml