apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-seller-service-cm
data:
  server.port: "8080"

  spring.application.name: emp-seller-service
  spring.jpa.generate-ddl: "false"

  spring.datasource.url: jdbc:mysql://emp-qa-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/seller?createDatabaseIfNotExist=true
  spring.datasource.username: root
 
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  #spring.jpa.hibernate.ddl-auto: validate

  opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  catalogue-service.url: http://localhost:8082
  catalogue-service.name: emp-catalogue-service
  user-service.name: emp-user-service
  user-service.url: http://localhost:8081
  #spring.kafka.consumer.bootstrap-servers: localhost:9092
  #spring.kafka.consumer.group-id: test-consumer-group
  #spring.kafka.consumer.auto-offset-reset: earliest
  #spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  