---
apiVersion: v1
kind: Service
metadata:
  name: emp-seller-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
    alb.ingress.kubernetes.io/healthcheck-path: /emp-seller-service/actuator/health
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emp-seller-service

