version: 0.2

env:
  git-credential-helper: yes
  variables:
    SERVICE_NAME: "prod-emp-seller-service"
    AWS_REGION: "ap-south-1"
    ECR_REGISTRY_URL: "656600766668.dkr.ecr.ap-south-1.amazonaws.com"

    
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
      - aws configure set default.region $AWS_REGION 
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain exportmarketplace --domain-owner 656600766668 --query authorizationToken --output text`

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL
      
  build:
    commands:
      - cd emp-seller-common
      - echo Building JAR file...
      - mvn clean install
      - echo Deploy completed on `date`
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain exportmarketplace --domain-owner 656600766668 --query authorizationToken --output text`
      - mvn deploy
    
      - cd ../emp-seller-service
      - echo Building JAR file...
      - mvn clean install

      - echo Building Docker image...
      - set -x
      - echo Fetching latest commitID...
      - git config --global --add safe.directory '*'
      - commitId=$(git log -n1 --format="%h")
      - date=$(date -u +"%Y%m%d%H%M%S")
      - imageId=$commitId$date
      - touch ~/imageId.txt && echo $imageId > ~/imageId.txt
      - echo $imageId
      - docker build -t emp-seller-service-ecr .
      - echo Tagging Docker image...
      - docker tag emp-seller-service-ecr:latest $ECR_REGISTRY_URL/$SERVICE_NAME:$imageId

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ECR_REGISTRY_URL/$SERVICE_NAME:$imageId
      - echo $imageId
      - IMAGE=$ECR_REGISTRY_URL/$SERVICE_NAME:$imageId
      - echo $IMAGE

