apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-user-service-cm
data:
  server.port: "8081"
  spring.application.name: emp-user-service
  server.servlet.context-path: /emp-user-service

  # spring.kafka.bootstrap-servers: 127.0.0.1:9092

  spring.jpa.generate-ddl: "true"
  spring.datasource.url: jdbc:mysql://emp-dev-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/usermanagement?createDatabaseIfNotExist=true
  spring.datasource.username: root
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  # eventuate.database.schema: eventuate
  spring.datasource.driver.class.name: com.mysql.jdbc.Driver

  # oms.domain.event.enable-dlq: "true"
  # oms.domain.event.retry.initial-interval: "1000"
  # oms.domain.event.retry.multiplier: "3"
  # oms.domain.event.retry.max-interval: "60000"

  # jwt.jwtTokenSecret: 2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
  # jwt.tokenExpirationMSec: "3600000"

