apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-notification-service-cm
data:
  server.port: "8085"

  spring.application.name: emp-notification-service
  spring.jpa.generate-ddl: "false"

  spring.datasource.url: jdbc:mysql://emp-dev-rds-mysql.chaqp2ysfjmh.ap-south-1.rds.amazonaws.com:3306/notification?createDatabaseIfNotExist=true
  spring.datasource.username: root
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  #spring.jpa.hibernate.ddl-auto: validate

  opentracing.jaeger.http-sender.url: http://localhost:16686/api/traces

  spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  spring.kafka.bootstrap-servers: 127.0.0.1:9092
  #spring.kafka.group-id: test-consumer-group
  #spring.kafka.auto-offset-reset: earliest
  #spring.kafka.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #spring.kafka.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  oms.domain.event.enable-dlq: "true"
  oms.domain.event.retry.initial-interval: "1000"
  oms.domain.event.retry.multiplier: "3"
  oms.domain.event.retry.max-interval: "60000"

  #Topic Details
  # kafka.load-topic: seller_create

  # Kafka Properties
  # kafkaconsumer.group-id: emp-notification-group
  # kafkaconsumer.bootstrap: 127.0.0.1:9092
  # kafkaconsumer.offset: latest

  #mj notification service config
  mj-email-service.name: mj-notification-service
  mj-email-service.url: http://10.132.83.4:3001
  mj-email-service.send-notification-url: /notification/send

  mj.notification.service.application-code: 2edsH3dn
  mj.notification.service.subapplication-code: gf3aV2sJ
  mj.notification.service.sms-template-code: generalSMSTest
  mj.notification.service.email-template-code: sendOtpEmail